// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgah6pR5_uDoUOnC1w5FVjT3RKS23tDrM',
    appId: '1:191298702466:web:9477642a801d0cbfe0f89b',
    messagingSenderId: '191298702466',
    projectId: 'todo-sysqbit',
    authDomain: 'todo-sysqbit.firebaseapp.com',
    storageBucket: 'todo-sysqbit.appspot.com',
    measurementId: 'G-Y0MCZEZ61V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB96licWWIywvAsJ_of5IDOHeAEuAtlMrk',
    appId: '1:191298702466:android:a60de430eb67f27fe0f89b',
    messagingSenderId: '191298702466',
    projectId: 'todo-sysqbit',
    storageBucket: 'todo-sysqbit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqumSjTCtnin61n7DxGQya41Zt3qq1nzU',
    appId: '1:191298702466:ios:8dd4414c2c0b8629e0f89b',
    messagingSenderId: '191298702466',
    projectId: 'todo-sysqbit',
    storageBucket: 'todo-sysqbit.appspot.com',
    iosClientId: '191298702466-m6svu2092h2h69g73674dk2cllr2du3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqumSjTCtnin61n7DxGQya41Zt3qq1nzU',
    appId: '1:191298702466:ios:8dd4414c2c0b8629e0f89b',
    messagingSenderId: '191298702466',
    projectId: 'todo-sysqbit',
    storageBucket: 'todo-sysqbit.appspot.com',
    iosClientId: '191298702466-m6svu2092h2h69g73674dk2cllr2du3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
